services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ~/docker_data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - franchise_web_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - franchise_web_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/docker_data/redis:/data
    networks:
      - franchise_web_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - franchise_web_network

  franchise-backend:
    container_name: franchise-backend
    image: franchise-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: docker
      DATABASE_URL: postgres://admin:admin123@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - franchise_web_network

networks:
  franchise_web_network:
    external: true
