services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ~/docker_data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - franchise_web_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - franchise_web_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ~/docker_data/redis:/data
    networks:
      - franchise_web_network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - franchise_web_network

networks:
  franchise_web_network:
    external: true
