ALTER TABLE brands
ADD CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES companies (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;

ALTER TABLE brands
ADD CONSTRAINT fk_industry FOREIGN KEY (industry_id) REFERENCES industries (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;