basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Web API
  version: "1.0"
paths:
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: test
      produces:
      - application/json
      responses: {}
      summary: Test
      tags:
      - Test
swagger: "2.0"
